### ISSUE TITLE
Parity with PasswordMaker Pro

### ISSUE THREAD

**Issue by JProffitt71** [webful-ltd/passwordmaker#2]
This is an awesome app, but right now I can't use it because it doesn't support the same settings / profiles that I use on my desktop. At the very least, it should support using multiple profiles, modifiers, usernames, arbitrary prefix and arbitrary suffix, and importing profiles from the extensions.

**Comment by NoelLH** [comment]
Hi @JProffitt71, thanks very much for the feedback.

Please don't take this at my not being interested but I'm going to close this issue, just because I think it's very broad, so we could only realistically prioritise and add everything you mention if split into much smaller, more specific issues. If you think it's helpful to also use a Label like `pwmaker-pro-parity` to group such issues, I'm happy to do that once they're created, but first I think we'll need much more detailed issues with a full explanation of each feature - something I'm not in a position to do right now.

As I've noted in the app microsite's [Limitations](https://passwordmaker.webful.uk/#limitations) section, for now I have intentionally prioritised ease of use over having every feature that long-time users of other PWM protocol items might have had available. I'd like to add more features in one by one, perhaps in an opt-in Advanced menu, but only if there's evidence they're used or would be, and they're applicable to this type of app and still make sense in 2019. For example, adding MD4 would require a whole additional crypto library, just to add a less secure option that the industry should probably be discouraging. This is a step closer to feature parity but it makes the app bigger for everyone and less safe for those who use it. Of course not all features are like this, but this is why I think we need to be specific about each addition.

On a practical note I'm unlikely to have the spare time in the next several months to do anything beyond security updates and bug fixes, so I'd also like to get more of a sense that a few people are interested in each feature, and preferably helping to test or build it, before it's planned for dev. In particular, adding something like multi-profiles with an interface that isn't confusing is a _lot_ of extra complexity and work relative to what is currently a pretty tiny codebase. I think we'd need to think carefully about the maintenance commitment inherent in that while the project is still this small.

I'll happily prioritise pull requests from new contributors as I'd love to have your help in adding to the app. If adding to the code is not your forte, it would also be super helpful to open an issue with full detail about what a feature in other apps does precisely, and an idea of how you imagine it looking in an easy to understand mobile interface. Anything from a UX prototype to a sketch on a napkin is great!

I hope that makes sense and I really appreciate you checking out the app. Hope we can work together to make it better.

**Comment by NoelLH** [comment]
Hi @JProffitt71, hope you're keeping well. Just wanted to highlight that a v2 beta is now [on both app stores](https://passwordmaker.webful.uk/#beta) and I'm trying to tidy it up for the stable release now. Would be good to get your thoughts on whether it works for you now.

The [v2 milestone](https://github.com/webful-ltd/passwordmaker/milestone/1?closed=1) details what I included, and I think it includes most of what I understood from your list here.
